### PR TITLE
New chat

### PR DESCRIPTION
**Pull request by LesChats**
lot of small correction (friend list + auth)
added some function for chat
redirection at singing

### CODE REVIEW

**Comment by Ala-Na** [comment]
It's seems a lot of binaires files (not necessary) are present inside this PR =/ Otherwise, the work seems great ! =)

**Comment by LesChats** [comment]
those in the client directory ? they come from build.... maybe I should remove those 🤔

**Comment by Ala-Na** [comment]
I'm not sure there's anything to keep inside client directory. Maybe you can delete it and put thé path inside .gitignore

**Comment by LesChats** [comment]
delete is fine ;)

**Review by Ala-Na — APPROVED** [review]
Approved death of client folder 😈

**Pull request merged**
