### PR TITLE
add initial nest files

### PR DESCRIPTION
**Pull request by Reaster0**
add the basic firsts templates files that nest cli created using "nest new project"

### CODE REVIEW

**Comment by Reaster0** [comment]
empty gits are sad

**Comment by LesChats** [comment]
Should be in a file named "Backend"

**Comment by Reaster0** [comment]
you right
do you think this inital layout would be nice?
>Bakend -> nest cli files -> ...
>Frontend -> vue cli files -> ...
>docker-compose.yml

**Comment by Ala-Na** [comment]
It seems convenient

**Pull request closed without merging**
