### PR TITLE
[WIP] final version of WatchGame

### PR DESCRIPTION
**Pull request by Reaster0**
what do you think if this system?
the page game can take two querys
watch as a boolean (in fact it will alway be true because why add a query as false)
and matchid that is the match id that you want to watch
normally it would work without any trouble, i just need one thing on the backend :
when i send the message "followGame" trough the websocket, it should not close the socket if the id is incorrect, it should just do nothing (or send a message back false or something idc)
i've putted a workardound with a timer from now but i'll remove it when it's done

### CODE REVIEW

**Comment by LesChats** [comment]
Why do we need a query that's always true ?

**Comment by LesChats** [comment]
ok did what was asked on the back (could not test it) please confirm that is ok
Otherwise I cannot judge the pertinence of the general modification, Nadège should de be one validating the pr

**Comment by LesChats** [comment]
(if the match id is incorrect he just does nothing)

**Comment by Reaster0** [comment]
> Why do we need a query that's always true ?

it's just that if we don't put it well it's like putting it false so else you put it or you don't have to ;')

**Review by Ala-Na — CHANGES_REQUESTED** [review]
I can't approve of those changes: The whole system to invite someone to play from chat is down =(

**Comment by Reaster0** [comment]
we'll have to discuss tomorrow on how you do that, you code is still here just commented since i dont understand it but i feel that's not unmergable with the query system

**Comment by Ala-Na** [comment]
See PR #135

**Pull request merged**
